// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aywhrfnrsrakbgicaarv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5d2hyZm5yc3Jha2JnaWNhYXJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTE5OTIsImV4cCI6MjA2NDA4Nzk5Mn0.1w0x_yzG7ETP9NAP_kBhh5K1sAZRI6gLxwFyqxpL8Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);